### ISSUE TITLE
Research: Which tech to use for making connections (NFC, ultrasonic, other)

### ISSUE THREAD

**Issue by stellarmagnet** [BrightID/BrightID#17]
For making connections in close proximity, is there sufficient market support for NFC?

How well does ultrasonic perform relative to NFC?

See https://github.com/BrightID/BrightID/issues/37 for a discussion of ultrasonic tech.

Which should we support?

See https://github.com/BrightID/BrightID/issues/20 for a discussion of framework support.

**Comment by mradul** [comment]
There are a few concerns in using Ultrasound technology -

* The library is fairly new and the community is non-existent.
* There might be security issues. I'm not sure about the range of communication, but it is possibly larger than NFC. The communication, as it is just audio, can be listened by any other device, which is probably not a big issue. A bigger issue perhaps is that we'll need to come up with a certification scheme so that the listener can make sure that the sender is the intended one. This is perhaps readily supported in NFC somehow, I would think.
* This might not work well on all devices, which is the problem that we wanted to solve in the first place. Even worse is we'll not know on which devices it'll work and in which it'll not as it depends on the microphone capability of the device. On the other hand, if NFC is supported on a device, we can be assured that the functionality that we require would be supported on the device.

On the other side, it sounds much cooler to use ultrasound.

I think we should let this technology evolve while we make progress. We should keep an eye on it and should be able to swap the implementation of how connections are made, once we're ready to move forward with it.

**Comment by mradul** [comment]
There are a few concerns in using this technology -

* The library is fairly new and the community is non-existent.
There might be security issues. I'm not sure about the range of communication, but it is possibly larger than NFC. The communication, as it is just audio, can be listened by any other device, which is probably not a big issue. A bigger issue perhaps is that we'll need to come up with a certification scheme so that the listener can make sure that the sender is the intended one. This is perhaps readily supported in NFC somehow, I would think.
* This might not work well on all devices, which is the problem that we wanted to solve in the first place. Even worse is we'll not know on which devices it'll work and in which it'll not as it depends on the microphone capability of the device. On the other hand, if NFC is supported on a device, we can be assured that the functionality that we require would be supported on the device.

On the other side, it sounds much cooler to use ultrasound.

I think we should let this technology evolve while we make progress. We should keep an eye on it and should be able to swap the implementation of how connections are made, once we're ready to move forward with it.

**Comment by adamstallard** [comment]
Thanks @mradul it sounds like the proper thing to do would be support NFC first and have fallbacks.  Perhaps ultrasonic could be a fallback.

**Comment by adamstallard** [comment]
I added this https://github.com/BrightID/BrightID/issues/42 task for implementing NFC -- who wants to take a crack at it?

**Comment by mradul** [comment]
I'll take a stab at it this weekend.

**Comment by adamstallard** [comment]
implement NFC #42

research ultrasound #37
