### ISSUE TITLE
How do we make connections with "ultrasonic" technology

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#37]
Is there a library for this?

https://www.youtube.com/watch?v=w6lRq5spQmc

Can it be done with react-native?

See https://github.com/BrightID/BrightID/issues/20 for a discussion of react native support

**Comment by mradul** [comment]
There is a library - https://github.com/adhbh/react-sonic, with one contributor with one commit :)
But it is based on https://github.com/borismus/sonicnet.js. This blog post talks about the js library. I haven't had time to go through it yet, but it has the same youtube video :)
http://smus.com/ultrasonic-networking/

**Comment by mradul** [comment]
"One technical caveat is that microphones are sometimes not as capable as speakers, **especially in phones, since they are often optimized for human speech, which sounds fine with a lower sample rate.** In other cases, even though the hardware is capable, the firmware runs at a lower sample rate for energy efficiency. If this is the case, one of the devices will not be able to receive the wave and the sound-based connection will be one-way only."

**Comment by mradul** [comment]
There are a few concerns in using this technology -
* The library is fairly new and the community is non-existent.
* There might be security issues. I'm not sure about the range of communication, but it is possibly larger than NFC. The communication, as it is just audio, can be listened by any other device, which is probably not a big issue. A bigger issue perhaps is that we'll need to come up with a certification scheme so that the listener can make sure that the sender is the intended one. This is perhaps readily supported in NFC somehow, I would think.
*This might not work well on all devices, which is the problem that we wanted to solve in the first place. Even worse is we'll not know on which devices it'll work and in which it'll not as it depends on the microphone capability of the device. On the other hand, if NFC is supported on a device, we can be assured that the functionality that we require would be supported on the device.

I think we should let this technology evolve while we make progress. We should keep an eye on it and should be able to swap the implementation of how connections are made, once we're ready to move forward with it.

On the other side, it sounds much cooler to use ultrasound.

**Comment by NickXML** [comment]
I've spent some time looking at both ultrasound and NFC in the past.

Just be aware that in widespread use, phone-based NFC is not quite as easy
as it should be. The placement of NFC antennas within a phone can vary
widely. Between that, NFC's very short range on phones and the varying
thickness of phone cases, it can be a lot harder to get one phone to read
another than it should be. Most phone implementations are well below the
4-10cm range defined in the NFC spec.

As for ultrasound, in this case you can operate at frequencies well below
true ultrasound. Not sure how that impacts the choice of available
libraries. However, once you get above 18KHz, most people can't hear it
easily, and your volume is going to be low enough for this to not really be
audible. Most smartphone microphones easily read up to 20-21KHz. Due to
their size and type, they mostly do better with high frequencies than low
frequencies anyway.

The usable distance follows a roughly inverse square law, so it should be
fairly easy to find a level that is easy to use but hard to spoof. e.g.
12"/30cm.

You can test this yourself with any of the free spectrum analyzers and
signal generators on the various app stores.

One thing to look out for: there was an app called "Bump" a few years back
that used the sound of two phones tapping each other to exchange contact
info. The company was acquired by Google. I would imagine they have some
existing patents in this area. See
https://en.m.wikipedia.org/wiki/Bump_(application).



-Nick

____________________________

Sent from my mobile device. Please excuse typos and brevity.

This email and any files transmitted with it are confidential and intended
solely for the use of the individual(s) or entity to whom they are
addressed. If you have received this email in error please notify the
sender.

**Comment by mradul** [comment]
Thanks @NickXML for additional details. I didn't look into NFC. It seems that there might be incompatibilities between two devices supporting NFC. Since, we're going to support both NFC and ultrasound, I'll start looking into ultrasound first.

**Comment by mradul** [comment]
I looked at the react-sonic library and how we can utilise it for react-native. It seems that it would not be straightforward. In case of the browser, the AudioContext is provided by the browser via web audio api, which is then used to send the sound. I am not able to find anything similar for react-native. However, with react-native we can write android-native(Java) code to support this. We'll need to find a native audio api.
I'll try to dig deeper into it, but first I need to gain more experience with react-native.

**Comment by adamstallard** [comment]
Ultrasonic or audible data transfer is slow (25-50 bytes / second), so can only be used for discovery.  QR is an easier to code alternative for discovery.
