### ISSUE TITLE
Internationalization (100 - 200 Subs)

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#562]
Support different languages and formats for important strings and check a user's locale to use the best strings and formats.

**Comment by Neozaru** [comment]
Hello,

(as discussed in issue 561) I would be glad to research and propose a solution for this.
If implemented successfully, I can also participate in the French translation.

**Comment by Neozaru** [comment]
For information, I started working on this.
It is visible on : https://github.com/Neozaru/BrightID/tree/features/562-internationalization

Heads up :
- It is adding two new libraries : `react-i18next` (translation processing) and `react-localize` (locale detection)
- It is modifying a lot of files (most of the pages actually).
- It is adding a lot of `t('something')` instead of raw text in most rendering functions.
- It is adding `withTranslation()(class)` wrappers on some exported classes.
- It is adding `useTranslation()` hooks in non-class components.


I do manual testing with my personal Android phone set in French. I am not sure I will be able to run E2E tests on my end, although I am trying to make sure that the displayed text in English remains the same as before the translation (in case you use text-based selectors).

Anyway at this point there are so many files modified that I wonder if I should do multiple Pull Request and merge incrementally or merge everything at the end.

Open to feedback

**Comment by TripleSpeeder** [comment]
I'm stoked to see this @Neozaru, missing i18n was bugging me for a long time already!

I understand that this will be a huge diff since all UI files need to be changed. Maybe it makes sense to first do a PR that basically only adds the infrastructure (your commit https://github.com/BrightID/BrightID/commit/03fcbe203246941643b228b86b5c007c041384ce)?
When that is merged we can see how many conflicts come up with the other changes and split as needed. Unfortunately we don't have much separation in the React components, so most times UI and functionality is mixed in the same file. 

Regarding the E2E-tests: There are a few text-based matchers, but it should be easy to change them to use the i18n constants. So i don't see a big problem there (Actually using common constants instead of hardcoded strings in the tests will be a nice improvement :-)

**Comment by Neozaru** [comment]
> Maybe it makes sense to first do a PR that basically only adds the infrastructure (your commit [03fcbe2](https://github.com/BrightID/BrightID/commit/03fcbe203246941643b228b86b5c007c041384ce))?

Ok, I just did that : https://github.com/BrightID/BrightID/pull/569
(no conflicts, but new dependencies so good maybe to test on your own dev environment + devices I don't have such as iOS)

For the rest of the commits, when trying to merge `dev` (after the recent commits) into the head of my current branch I have only two conflicts on `ConnectionCard` and `MyCodeScreen` that I believe are trivial.
I think can merge `dev` (and solve conflicts) regularly to my big branch unless you don't really like to see merge commits in the history.

**Comment by TripleSpeeder** [comment]
Initial PR #569 has been merged to DEV. I think you can continue now with adding actual translation files @Neozaru

**Comment by TripleSpeeder** [comment]
Translation integration is fully functional. Closing this.
