### ISSUE TITLE
Don't rely on API to obtain IP of node/profile service

### ISSUE THREAD

**Issue by TripleSpeeder** [BrightID/BrightID#689]
**Current situation:**
 -> Client knows hostname of API node
 -> Client queries node API to get the IP Address to include it in the QRCode

**Proposal:**
 -> Client knows hostname of API node
 -> Client locally resolves hostname to get IP address for QRCode. This should happen everytime a QRCode is created, so always the current IP address is used.

**Benefits:**

- Completely removes the need for the node to provide the `ip` API and related environment vars
- Will make it possible to use nodes that have dynamic IPs with a dyndns setup, e.g. DAppNodes running at home
- We can keep using IP address in QRCode to keep the encoded data low

**Comment by adamstallard** [comment]
Using domains and then having scanner resolve them is the most likely to succeed. For example, user encodes "https://my.node.com", scanner decodes that, adds the standard api beginning "/brightid/profile" (or whatever) and makes the request.

We can have the qr encode either, and the scanner can easily check the length. If it's 4 bytes, it can treat it like an ip address, otherwise it can try to decode it as url string.
But since we are also controlling how QRs are encoded, the general strategy that is most likely to succeed is to always encode as a url string.
EDITED
If we accept both, then our list of BrightID nodes needs to indicate which can use ip addresses and which can't. That is the extra maintenance cost of having smaller QRs in some cases.

**Comment by TripleSpeeder** [comment]
Agree that ideally we would use full urls in the qrcode. I would also really like to be able to specify the port and protocol. I can see situations where port 80/443 is already in use.

We should analyze if there are other options to reduce the data size for the qrcode. 

Idea: The person creating the qrcode could upload all relevant information in a json file with a random name somewhere and just encode the url to the json file in the qrcode.

**Comment by adamstallard** [comment]
@TripleSpeeder 
> 
> We should analyze if there are other options to reduce the data size for the qrcode.
> 
> Idea: The person creating the qrcode could upload all relevant information in a json file with a random name somewhere and just encode the url to the json file in the qrcode.

Originally I encoded the QRs with 4 bytes for the IP, 16 bytes for an encryption key, and 9 bytes for a unique identifier for looking up the profile in the profile service (which had a TTL).  You can see the code to do that here  https://github.com/BrightID/BrightID/blob/2354542e048ef2f525d88250ea323354cfe73a00/BrightID/src/components/NewConnectionsScreens/actions/genQrData.js#L17-L20

29 bytes was carefully chosen to keep the QR small.  You can see some of the discussion here about testing the density of the resulting QR code here keybase://chat/brightid#frontend/851

For example,
>Here's an example of a string with the ipaddress ascii-encoded as 4 bytes, one 16 byte uuid (as base64), and one 16 byte shared key (as base64)
>½+¾=+vmP//xVrIr3d29wEQ4Cy9N8qRd1aZ07dZlQ6gUlZss=At83Il8JMSJfKZ702hE9jqM7YeQdLUtm+YzxXxIwyfQ=
>I pasted this into https://www.qr-code-generator.com/ and I got an image that looked like this.  Do you think that's too dense?

The profile service was designed to contain all the "relevant information."

We also discussed using iso-8559-1 encoding instead of B64 to use 25% fewer bytes.

I'm not sure what you're putting in the QR code these days, but that's the historical reference.

**Comment by TripleSpeeder** [comment]
> Originally I encoded the QRs with 4 bytes for the IP, 16 bytes for an encryption key, and 9 bytes for a unique identifier for looking up the profile in the profile service (which had a TTL). You can see the code to do that here

Since the addition of group connection and channels there is quite a bit more information required. QRCode currently contains:
- aeskey
- channelID
- profileID of channel creator
- IP Address of profile service
- Channel type
- creation timestamp
- ttl

Encoding of qrstring is done in `utils/channels.js`:

https://github.com/BrightID/BrightID/blob/dcc1c1d514bc53acce4a86b516bc12ea61a5fbeb/BrightID/src/utils/channels.js#L44-L65

What I'm thinking is that the user creating a channel can store most of this information in the channel instead of in the QRCode. So there could be a new file `channelInfo.json` in the channel, e.g.
```json
{
  "version": 1,
  "channelType": "SINGLE",
  "timestamp": 123456789,
  "ttl": 900,
  "initiatorProfileID": "uuid-of-channel-creator-profile"
}
```

This way we can reduce the data that needs to be contained in the qrcode to just these two values:
 - full url to profile service (instead of IPAddress)
 - aeskey 

**Channel creator needs to do:**
1. Encrypt and upload profile to channel as usual
2. Create `channelInfo.json` and upload it to channel
3. Create QRCode containing only encryption key and url

**The scanner then needs to do the following:**
1. Scan QRCode -> Now he knows the URL and the encryption key
2. Fetch channelinfo by requesting the well-known file "channelInfo.json" from the channel -> Now he knows all other information
3. Continue workflow as usual
