### ISSUE TITLE
Don't show "[object Object]" in alerts

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#729]
Apparently, we're trying to include a human-readable error message in some alerts, but the result object in whatever templating system it's using on the json file of locale strings just shows [object Object] instead. https://github.com/BrightID/BrightID/blob/52ef8d3ef7296ef71978a4d498e7421556aa17ac/BrightID/locales/en/translation.json#L52
![Screenshot_20210123-101832_BrightID](https://user-images.githubusercontent.com/205792/105613337-c0606900-5d76-11eb-97d1-cbd9e55d6111.jpg)

In this case, `result.message` might be appropriate to use.  It might render as `"only three contextIds can be linked every 24 hours"`

**Comment by abramsymons** [comment]
The root of the issue is that we are storing an object with errorNum and message in latest release of node as operation result.
I solved this issue by this commit:
https://github.com/BrightID/BrightID/commit/0ff737b10708da41d7408cbb7d1e20f794ead194
but I mistakenly pushed that to the master instead of dev.
Can this make a problem? @TripleSpeeder
